### ISSUE TITLE
Could not load shared library

### ISSUE THREAD

**Issue by d-chambers** [eqcorrscan/EQcorrscan#112]
Running Ubuntu 16.04 I followed the instructions listed [here](http://eqcorrscan.readthedocs.io/en/latest/intro.html#installation-updated-for-version-0-2-0), including creating a conda virtual env and installing fftw. 

I then cloned the current repo and tried to run the test suite but I get many failing tests with the following errors:

'Could not load shared library "libutils.cpython-36m-x86_64-linux-gnu.so".\n\n /media/data/Gits/EQcorrscan/eqcorrscan/lib/libutils.cpython-36m-x86_64-linux-gnu.so: undefined symbol: GOMP_parallel_sections'

Next, I tried deactivating the conda env and installing from source (master) using:
```bash
python setup.py install 
```
The installation seems to have worked but re-running the tests the same problem arises.

**Comment by calum-chamberlain** [comment]
Rubbing the tests requires you to run

python setup.py build_ext --inplace

Calum Chamberlain
Postdoctoral Fellow, Seismology
Victoria University of Wellington
Sent from mobile.

________________________________

**Comment by d-chambers** [comment]
Ok I ran the build_ext command, then tried to run the tests and get the same error. This time I installed eqcorrcan with the develop flag, not sure if that makes a difference.

**Comment by calum-chamberlain** [comment]
Does the file in question exist? If not then the build has gone wrong. If yes then something has gone wrong in the linking, if this is the case you should paste here the GCC lines.

Calum Chamberlain
Postdoctoral Fellow, Seismology
Victoria University of Wellington
Sent from mobile.

________________________________

**Comment by calum-chamberlain** [comment]
Ah, on reading more closely, it looks like you don't have the openmp libraries installed? I had thought this was standard in gcc, more info to follow (and will update docs once we get this working).

p.s. eqcorrscan is now on condo-forge, and comes with fftw and openmp when installing from there, but you can't run the tests from there...

**Comment by calum-chamberlain** [comment]
It looks like a linking error to the openMP libraries, but I don't know why it would be (tests on 16.04 run fine with standard setups).  Can I check that gcc is the compiler that gets called by setup.py build_ext? It would usually be gcc unless you built your Python in an interesting way (although the current method also works for intel compilers).

**Comment by d-chambers** [comment]
I am just running anaconda with python version 3.6, shouldn't be anything unusual about it. 

It turns out eqcorrscan/lib/libutils.cpython-36m-x86_64-linux-gnu.so doesn't exist, not sure what that means as far as possible failures in the compile chain.

**Comment by calum-chamberlain** [comment]
Very strange, the gomp missing error sounds like it found the shared library, but missed the link.
Could you paste the output from:

`python setup.py build_ext --inplace`

Calum Chamberlain
Postdoctoral Fellow, Seismology
Victoria University of Wellington
Sent from mobile.

________________________________

**Comment by calum-chamberlain** [comment]
Okay, so I can recreate this error when I install gcc using conda, rather than using the system version of gcc.  What I actually did was:
 1. create a new conda env (without installing gcc via conda)
 2. build eqcorrscan using pip
   - tests pass
 4. installed gcc via conda
   - tests fail with missing reference to GOMP functions
 5. installed openMP from conda
   - tests fail with same errors
 7. clean out built files (remove build directory and any possible shared object in lib)
 6. rebuild eqcorrscan with pip
   - tests pass

As follows:
```bash
conda create -n eqcorrscan python=3.6 colorama numpy scipy matplotlib obspy bottleneck pyproj
source activate eqcorrscan
pip install .  #run from git repo directory
python eqcorrscan/tests/correlate_test.py
# Pass
conda install gcc
pip install .  -U --no-deps
python eqcorrscan/tests/correlate_test.py
# Fail
conda install openmp
pip install .  -U --no-deps
python eqcorrscan/tests/correlate_test.py
# Fail
rm -r build
rm eqcorrscan/lib/libutils.cpython-*.so
pip install .  -U --no-deps
python eqcorrscan/tests/correlate_test.py
# Pass
```

In my case, the library built fine, but was built with a different version of libgcc and libgomp than in the conda env, which is fine - I don't know if this holds for you? Did you install gcc via conda after building the libraries?

You can check which gcc is being used by running `which gcc`.

Also, if I make an environment including gcc:
```bash
conda create -n eqcorrscan python=3.6 colorama numpy scipy matplotlib obspy bottleneck pyproj gcc
```
It runs fine (and builds using the conda gcc).

**Comment by calum-chamberlain** [comment]
Also note that you should be fine using the system gcc (which should have happened using the instructions on the website, so I don't know what happened there originally?).
When you update from the git repo you will need to clean out the built shared objects first, otherwise they will not be rebuilt.

**Comment by d-chambers** [comment]
Okay, it seems to work now with your suggestions. I think my original attempt to install eqcorrscan, without a virtual env, would have been similar to where you were at in step 4 listed above. The build directory would have existed, which was probably the reason the subsequent efforts failed with environments that should have worked had the build been removed. 

Since compilation time is very small maybe build should be removed by default? 

Thanks for your help.

**Comment by calum-chamberlain** [comment]
I think removing build by default would be a good idea - might have to dig into setup-tools a little more to work out how that should be done.
