### ISSUE TITLE
match_filter_test fails in 0.3.1 on RedHatEnterpriseServer 6.9

### ISSUE THREAD

**Issue by flixha** [eqcorrscan/EQcorrscan#252]
**Describe the bug**
The match_filter_test does not currently complete successfully on my machine(s). Upon encountering the problem I downloaded & installed EQcorrscan 0.3.1 both directly through conda and cloned the master branch, but both times the test failed.

In particular, I first encountered problems with match_filter when trying to detect events using the tribe.detect(xcorr_func='fftw'...), which returned some additional detections close to the limits of the continuous data compared to tribe.detect(xcorr_func='time_domain'...). Those additional detections were likely wrong and were not particularly reproducible. However, I'm not sure how far the errors in the match_filter_test are affected by or limited to this very problem.

Does this error occur on other systems as well, and if not, what other details can I provide? Cheers!

**To Reproduce**
run match_filter_test.py

**Expected behavior**
Successful completion of match_filter_test.py without errors.

**Desktop (please complete the following information):**
 - Operating System: RedHatEnterpriseServer 6.9
 - Python version: 3.6.3
 - EQcorrscan version: 0.3.1

**Additional context**

**Comment by calum-chamberlain** [comment]
Could you paste the failed test output, and the output of `conda list` - I will try and reproduce, which will involve trying to find a RedHat machine! Joys.
Final question, did you at any point install fftw from any other source, or only from conda?

**Comment by calum-chamberlain** [comment]
When you say:
> which returned some additional detections close to the limits of the continuous data 

what do you mean?

**Comment by calum-chamberlain** [comment]
Oh, and no, the tests pass on:
- [Ubuntu 14.04](https://travis-ci.org/eqcorrscan/EQcorrscan/jobs/402530108) - note fails in this are due to network timeouts in FDSN.
- Ubuntu 16.04, locally on my quad-core laptop, and on the VUW 80-core server
- Debian on Odroids and Raspberry Pis (with non-intel chipsets).
- [Mac OSX](https://travis-ci.org/eqcorrscan/EQcorrscan/jobs/402530110) (darwin 15.6 - El Capitan according to [wiki](https://en.wikipedia.org/wiki/Darwin_(operating_system))
- [Windows](https://ci.appveyor.com/project/calum-chamberlain/eqcorrscan-jsycv/branch/master) - unsure on version.

I found a server running RHEL 6.7, I will experiment and report back.

Thanks for reporting this bug - if anyone running EQcorrscan on RHEL wants to chip in with whether their test results that would also be great.

**Comment by calum-chamberlain** [comment]
@flixha Did you manage to get those details?

>Would you be able to:
>  1. Report what the fail is (output from running python eqcorrscan/tests/match_filter_test.py);
>  2. Report the output from conda list;
>  3. Check what libraries your libutils.* file is linked against;
>  4. Provide some idea of the chipset.

I would really like to fix this if we can.

**Comment by calum-chamberlain** [comment]
@flixha I found a few bugs in #260, which might have been the source of this issue, would you be able to checkout the `develop` branch and test that on your machine to see if the issue has been fixed?

**Comment by calum-chamberlain** [comment]
Closing this because of lack of response. Reopen if you still have this issue and want to help fix it.
