### ISSUE TITLE
installation error: Matplotlib is not build with the correct FreeType version to run tests.

### ISSUE THREAD

**Issue by Geodesyman** [eqcorrscan/EQcorrscan#282]
Hi everyone!

I'm new to this so apologies if this is user error. I'm trying to test my install of EQcorrscan. I followed the instructions for install using conda and everything seemed to be going well but when I ran " test_eqcorrscan"  I got the following error message:
"/anaconda3/envs/eqcorrscan/lib/python3.6/site-packages/matplotlib/_init__.py:1472: UserWarning: Matplotlib is not build with the correct FreeType version to run tests."

Not sure what I should do next so any help would be much appreciated. I'm running on ubuntu 18.04

Thanks.

**Comment by calum-chamberlain** [comment]
Hi! That is a strange one. Two things though:
1.  This looks like it is just a warning (rather than an error), so did the tests continue running? It might be helpful to paste the output from the tests here.
2. Could you also paste the output from `conda list -n eqcorrscan` - that should list all the packages you have installed in the conda environment (it looks like you called it eqcorrscan).

Thanks for the interest in EQcorrscan, I hope it can be of some use to you!

**Comment by Geodesyman** [comment]
Thanks for your reply. @calum-chamberlain 
1. tests did not continue running ,the output is here.
[tests_out_ubuntu1804.txt](https://github.com/eqcorrscan/EQcorrscan/files/2627533/tests_out_ubuntu1804.txt)


2. the output from `conda list -n eqcorrscan` is 
[condalist_ubuntu1804.txt](https://github.com/eqcorrscan/EQcorrscan/files/2627534/condalist_ubuntu1804.txt)

i also try to install eqcorrscan on my mac which is OSX 10.13.2. The same error happened. 

the output from `test_eqcorrscan.py`  on mac is 
[tests_out_mac.txt](https://github.com/eqcorrscan/EQcorrscan/files/2627539/tests_out_mac.txt)

output from `conda  list -n eqcorrscan` on mac is 
[condalist_mac.txt](https://github.com/eqcorrscan/EQcorrscan/files/2627541/condalist_mac.txt)

Thank you for your help!

**Comment by calum-chamberlain** [comment]
Ah, looks like I haven't updated the docs to add pytest-mpl as a test dependency.  Can you try installing that and re-running?
```bash
pip install pytest-mpl
```
If it works I will update the docs. Sorry! Testing the plotting is quite a recent thing and I haven't seen it fail like this before!

**Comment by Geodesyman** [comment]
Thanks for your suggestions. @calum-chamberlain

I install the pytest-mpl and re-run the test, however, It still has some error. the output is larger than 10M that I cannot upload it.  I have email it to your address "calum.chamberlain@vuw.ac.nz"

Thanks a lot !

**Comment by calum-chamberlain** [comment]
Ah, it looks like it isn't collecting the tests properly - when did you download the test script? It looks like it isn't running the most recent version (it doesn't say anything about the conofig files that it needs).

**Comment by calum-chamberlain** [comment]
@Geodesyman any luck?

**Comment by Geodesyman** [comment]
@calum-chamberlain 
I downloaded the test script just half of a month ago.  it may be my operating system error. I am going to reinstall my operating system and EQcorrscan.  Recently, I am performing GNSS observation in other city. I will reply you later.
thank you for your help!

**Comment by calum-chamberlain** [comment]
I don't think it would be your operating system. And that sounds like a recent enough version of the test script. I am in the process of generating a new release which will include the test-script with it, so you won't have to download a test-script.  I think this error might be happening because there is a test-script packaged with 0.3.2, which may be getting incorrectly called.
Maybe when you are ready to try again the new release will be out and you can try that.
Good luck with your observations!

**Comment by Geodesyman** [comment]
@calum-chamberlain
I have try the least release, however, it still have some error. I install the pytest and other test dependency with : 
`pip install pytest pytest-pep8 pytest-cov  pytest-mpl`
the output of the test script is : 
![e4bec76b8c905ed31c5eaabeb4012c52](https://user-images.githubusercontent.com/9856306/49775206-591c0200-fd32-11e8-88f6-60dfe6930bc0.jpg)
the output from conda list -n eqcorrscan is:
[](url)
[condalist_ubuntu1804.txt](https://github.com/eqcorrscan/EQcorrscan/files/2665764/condalist_ubuntu1804.txt)

if you are willing, you can control my computer with the teamview. I can give you my teamview id and password though email, in order to solve this problem.

Thanks a lot !

**Comment by calum-chamberlain** [comment]
Thanks for that! Three of those are network connection issues and not to worry about. The last is something I am working on and not a major problem.
