### ISSUE TITLE
Speed bottleneck in tribe.detect()?

### ISSUE THREAD

**Issue by jojomale** [eqcorrscan/EQcorrscan#431]
Hi, I am using the detect-method of the Tribe class and I wonder if I am doing something wrong because it takes ages to complete. The Tribe contains 2 templates on 2 stations. The continuous data is 14 days and I want to process it in  chunks of  24h.  
I feed the whole stream to the function and obviously it is capable of processing it, so I assumed that is the intended way to do it. 
The correlations (and peak finding?) are done within minutes  (I use 4 cores on normal PC). But then the process takes ages for the last few lines of the code which runs a method `family._uniq()`. This seems to creates a huge bottleneck since it iterates over lists of families and detections and checks for duplicates. And these lists in my case have millions of entries.

Since you can request to save the party before this "sanity check" I could see that it is actually a necessary step. But I am wondering if that is the best place to do it or if it can be accelerated.

For me, it is actually faster to slice the data outside of `detect()` and pass only 24h of data and stack the parties. Although this contradicts my understanding of the funcionality.

**Comment by calum-chamberlain** [comment]
Kia Ora!

Thanks for getting in touch. There are a few things here:
1. Yes you can pass as much data as you like to `.detect`, it will split those data into chunks of 24 hours (in your case, assuming that your `Template`s are processed from 24 hours of data) with a small overlap to avoid missing detections. This is the preferred way to do this, but is often not used directly because reading in all your data at once can be quite memory intensive. Personally I often run each day individually and force an overlap manually outside of `.detect` to cope with memory limitations (running a few 100k templates over 30 channels), which is your final suggestion.
2. It is good to hear everything runs smoothly, up to the call to `_uniq`. The main reason that this is not accelerated in any way is because I have never found this to be a bottleneck before. By all means you can try to accelerate it - the slowest part will be the comparison of detections (`Detection.__eq__`) - a possible way to improve this would be to make `Detection` objects hashable. 
3. The number of detections, and therefore bottleneck in `Family._uniq` suggests that you may be over-detecting, with too low a threshold.

In this response I'm assuming that you are running the latest version of EQcorrscan, although I don't remember the last time we changed `Family._uniq` of `Detection.__eq__`.

**Comment by calum-chamberlain** [comment]
By the way, I'm in the field for the next few weeks, so will be slow to respond.

/ooo today until 30th October

**Comment by calum-chamberlain** [comment]
@jojomale have you made any progress with this? Did you check your detections and see whether your detection threshold was reasonable? 

I'm happy to receive accelerations on `._uniq()`, and help with this if needed!

**Comment by jojomale** [comment]
Hi,
Since the "workaround" with passing only 24-h chunks worked so well, I haven't really looked further into the issue. Nevertheless, here are a few thoughts and comments:

1. My detection threshold is fine I think. At least the final number and quality of detections is good. 
2. Based on the performance of the "workaround", I was thinking that `._uniq()` should be called somewhere on the level where these chunks are produced. Although, I haven't quite figured out where the data is actually cut into chunks for processing within `detect()`. I guess it is happening in `_group_detect`.  But I suspect this would be a significant restructuring of the code. 
3. While tinkering on a showcase example, I noticed that if you run `detect()` directly on a `Template` object `.uniq()` is not called upon the resulting `Family`. So in my case, I end up with two different sets of detections depending on whether I run the template alone or as part of a tribe. In the former case, the Family contains a lot of duplicate detections. I find that outcome a bit inconsistent.
4. I am not sure if these duplicate detections are the result of my data and workflow. So far I could not figure out where they come from. It looks like every detection occurs twice except for those of the last chunk. If I pass only 24-h I don't have duplicates at all.
5. I am using version 3.3.3  at the moment but I think the functions are largely the same even though they are distributed among several files in the newer version.

**Comment by calum-chamberlain** [comment]
Thanks for that:

1. Grand!
2. I don't think that would be that much of a restructure, and I will look into it.  **TODO**
3. That does seem inconsistent and should be fixed! Thanks for brining this to my attention! **TODO**
4. I wouldn't be able to comment on that unless I saw your code, happy to look over it if you want.
5. Mostly the API is the same between 3.3.3 and the current version, *BUT* you would see a significant speed-up by switching to the latest release - in particular PR #285 led to a significant drop in memory consumption and a speed-up. Resampling is also faster. I would strongly recommend upgrading, or at least creating a new conda environment with 0.4.2 and trying your code using that to see if you would need to change anything. Ideally your code will just work and you get free speed.

**Comment by calum-chamberlain** [comment]
Partially addressed in #511 - closing.
