### ISSUE TITLE
[HELP] P and S picks in Lag_calc issue

### ISSUE THREAD

**Issue by PerrochL** [eqcorrscan/EQcorrscan#434]
# What do you need help with?
I am working with my own data. I managed to construct a Tribe and make detections. Now I want to use Lag_calc and everything runs smoothly, but the S and P picks are identical in the repicked_catalog. 
I already checked that my picks have different times in the catalog I use, and it's the case.
For my catalog, I used the select.out file from seisan that I converted to a xml file.

(Also, another problem is that when constructing the tribe, I am unable to use an other option than swin=P_all. 
If I use any other option, it returns an empty tribe... So I guess that something must be going on with my initial catalog, but I don't know what)

# Provide an example so that we can reproduce your problem
Attached is the script I run
[PerrochL_EQcorrscan.txt](https://github.com/eqcorrscan/EQcorrscan/files/5400196/PerrochL_EQcorrscan.txt)

# What help would you like?
If possible get a corrected repicked_catalog...

# What is your setup? (please complete the following information):**
 - Operating System: Windows 10
 - Python version: 3.7
 - EQcorrscan version: 0.4.2

**Comment by calum-chamberlain** [comment]
Hi, thanks for getting in touch. I suspect that this is related to how your picks are labelled in your catalog - both the issue with the lag-calc picks and template creation suggests this.

Would you be able to share your catalog, or (probably preferably first) a single event. It is possible that the `pick.phase_hint` is not set as EQcorrscan expects it.

Apologies if I am a little slow to respond, I'm in the field at the moment.

**Comment by PerrochL** [comment]
Hello, and thanks for the reply !
I attach here the catalog, which is the select.out file from seisan, before converting it to .xml. (Maybe it's something during this conversion that goes wrong)
I already checked the phase_hint, but did not see anything special about it...

Thanks again to have a look !

[catalog.txt](https://github.com/eqcorrscan/EQcorrscan/files/5415228/catalog.txt)

**Comment by calum-chamberlain** [comment]
Can you send the quakeml it looks like that is what you use to make the templates.

CJ Chamberlain, out of office

________________________________

**Comment by PerrochL** [comment]
Here it is

[cat.zip](https://github.com/eqcorrscan/EQcorrscan/files/5417888/cat.zip)

**Comment by calum-chamberlain** [comment]
Kia Ora, I just had a quick look, and while the phase hints look okay, the `waveform_id` looks odd - EQcorrscan checks for full channel codes, and doesn't cope with wildcards there.  It looks like your conversion has added a `?` wildcard as the second character of the `pick.waveform_id.channel_code` field.  

Can you go through and change your `pick.waveform_id`s so that they match your data and try again. You will need to include the `network_code`, `station_code`, `location_code` and `channel_code` as they are in your data for your picks to match correctly to data. 

This is one of the issues with using incomplete metadata unfortunately.

**Comment by PerrochL** [comment]
Yes, I saw this and changed the pick.waveform_id only after creating the tribe. This is why it didn't work!

Tried it directly on the xml catalog, before creating the tribe and now I get the correct picks ! 
Thank you very much for your time!

**Comment by calum-chamberlain** [comment]
All good.

Just out of curiosity, why did you not just read in the select.out file using Obspy? Is there something missing in Obspy's readng of Nordic files that you think should be added? Only asking because i helped write the Nordic IO for Obspy, and we are always keen for constructive feedback from users.

**Comment by PerrochL** [comment]
Because when I use directly the read_nordic I get an error... I managed to get around the error by marking the GAP line as a comment and then it works. But then information on the error is missing...and I don't want to do it everytime I select events in seisan.

But for some reason that I don't understand - I justed tried it to check what was the exact error I get - and it worked !
(it has been giving me an error for 3 months...)

**Comment by calum-chamberlain** [comment]
Interesting - we do continue to update things in the Nordic IO - maybe you updated your Obspy since you last ran into the error?

If you do run into any issues please do let us know at the Obspy repository.

I'm going to close this issue now.
