### ISSUE TITLE
Should the self-detection time of a template be independent of other templates in the tribe?

### ISSUE THREAD

**Issue by flixha** [eqcorrscan/EQcorrscan#438]
I ran some tests to let an event template detect itself in continuous data. But depending on the station choice and what other templates were in the tribe that I used, I got different detection times (11 s apart). I tried to debug this and believe I have an idea of what's happening. I'm wondering whether this is the expected behaviour or not. If it's not expected, it would be nice if you have some feedback for how to solve it.

### Issue description:
- Let's detect an event with a template of itself in continuous data. There are two templates, A and B, with template A being created from the event that we want to detect itself.
  - the earliest trace (i.e., pick) in the templates is for station DRUM, but for that station there is less than 80 % data during that day
  - template B contains a pick + trace for station INVG, but there is not such pick or trace for template A
  - both templates contain pick+trace for stations EKB10.BHZ and ESK.BHZ, but template B contains EKB10.BHZ twice because it's a 1-comp station with P and S-pick on the same channel

- In case 1
  - I use a tribe of two templates, A and B , with template A created from the event itself.
  - for template A, `eqcorrscan.utils.preprocessing._prep_data_for_correlation` removes the traces for DRUM and adds two NaN-traces (for EKB10.BHZ and INVG.BHZ, with both traces starting at 18:14:42
  - the stream contains traces EKB10.BHZ x2, ESK.BHZ, INVG.BHZ
  - the event is detected at **18:14:42** (hh:mm:ss, same a P-pick on DRUM), and the detection-channel list contains [('EKB10', 'BHZ'), ('ESK', 'BHE'), ('ESK', 'BHN'), ('ESK', 'BHZ')]
- In case 2
  -  I use a tribe of one template, A, created from the event itself.
  - for template A `eqcorrscan.utils.preprocessing._prep_data_for_correlation` removes the trace for DRUM and INVG, so that the earliest remaining trace starts at 18:14:53
  - the stream contains traces EKB10.BHZ, ESK.BHZ
  - the event is detected at **18:14:53** (hh:mm:ss, i.e., P-pick on EKB10), and the detection-channel list mentions [('EKB10', 'BHZ'), ('ESK', 'BHE'), ('ESK', 'BHN'), ('ESK', 'BHZ')]

### Analysis / Consequences:
So as I understand, the difference in detection time is because in case 2 with only one template for detection, there are no NaN-channels in the template. Hence the earliest trace in the template starts at 18:14:53.0 and that is then the detection time. If I try to use the detection from case 2 in `lag_calc`, I get the wrong picks. So I would say that also in case 2, we should get 18:14:42 as detection time, because the detection time should not change because there are other templates in the tribe or not.

### Possible solution:
As a possible solution, one could do a check at the end of the template-preparation in `eqcorrscan.utils.preprocessing._prep_data_for_correlation` that does as follows:
- if the earliest trace of the original template is to be removed because there is no continuous data for it
- then don't remove it, but instead add a NaN-channel for that station-channel to the stream

**Comment by calum-chamberlain** [comment]
Morning @flixha - I think your conclusion is probably right - that this is due to the earliest trace being thrown out completely in one case, and being converted to NaN in the other due to poor data quality in the continuous data. Having a different result depending on what templates are used is certainly not what we want, nor is getting the wrong pick times from `lag_calc`! Thanks for spotting this!

Your solution is certainly workable, but adds quite a lot of computational overhead and so probably isn't the most desirable way to fix this long-term, but if it helps you get your case up and running then go for it on your local code.

I think this should be fixed fairly urgently as it is something that I think would not be obvious and could be very frustrating for many people. @flixha would you be able to start a PR with a test-case that demonstrates this, e.g. a test that runs the single template and two template tribes and checks that they have the same detection times (this test should fail), then we can work on a solution in that PR.

**Comment by flixha** [comment]
Hi @calum-chamberlain, thanks for your quick reply!
I will create and upload the test case soon (guess on Monday), and yes I can start the PR for that where we can work on the fix. I also thought that the NaN-trace is not optimal from the overhead-point. But it seems to me right now that we would otherwise need to provide extra metadata with the detections to make them comparable, which would change a lot more in terms of class properties and detection file contents..

**Comment by calum-chamberlain** [comment]
Thanks, and yes, it may be the simplest way. Maybe we will end up going with that to get it fixed with an eye to a better solution later.

CJ Chamberlain, out of office

________________________________
