### ISSUE TITLE
clustering.distance_matrix does not handle shift_len > 0 well

### ISSUE THREAD

**Issue by flixha** [eqcorrscan/EQcorrscan#451]
**Describe the bug**
`eqcorrscan.utils.clustering.distance_matrix` offers an option `shift_len`, but because the function enforces strict symmetry for the correlation / distance matrix, this option effectively can't be used for template-streams with `shift_len > 0`.

**To Reproduce**
Here a two-template, single-trace example from `ClusteringTests.test_distance_matrix` with shift_len=0.1:
```python
import glob, os
from obspy import read
from eqcorrscan import tests
from eqcorrscan.utils.clustering import distance_matrix

testing_path = os.path.join(os.path.dirname(tests.__file__),
                            'test_data', 'WAV', 'TEST_')
stream_files = glob.glob(os.path.join(testing_path, '*DFDPC*'))[0:10]
stream_list = [read(stream_file) for stream_file in stream_files[1:3]]
stream_list = [st.select(station='EORO', channel='SHZ') for st in stream_list]

dist_mat = distance_matrix(stream_list=stream_list, cores=1, shift_len=0.1)
```
This will cause an error at [clustering.py:L144](https://github.com/eqcorrscan/EQcorrscan/blob/a56711221e5fb0939856b09e9b89f49f5dfb27e4/eqcorrscan/utils/clustering.py#L144) because the correlation matrix in this case basically never fulfills a strict symmetry requirement.

**Expected behavior**

The main goal is to let the function handle shifts other than zero without throwing an error.  The error is due to `cross_chan_correlation(st1, st2, shift_len=0.1))` vs. `cross_chan_correlation(st2, st1, shift_len=0.1))` resulting in a difference in cross-correlation value. I believe that the difference is caused by an edge effect: As these functions are designed for template-streams which are already trimmed to the pick plus `template_length`, introducing any shift will cause the correlation of Zeros (or NaNs).

I see a few options for what exactly should happen internally and then be returned from the function; I'd like to get your input on what you think is most appropriate / useful:

1. Simplest fix for now: require strict symmetry only if `shift_len=0`; otherwise either return the asymmetric matrix or force perfect symmetry as is done now.
2. By using `shift_len` other than zero, `eqcorrscan.utils.clustering.distance_matrix` could use a value equal to `shift_len` as padding around the traces to avoid any NaN / Zero-correlations. Then we'd just have to tell the user (and maybe check in the function) that they need to create templates which use `prepick = shift_len` and `template_length = template_length + 2*shift_len`
3. Provide the function with longer streams so that it can do its own trimming or padding rather than taking the fixed-length template streams.

**Desktop (please complete the following information):**
 - Operating System: RHEL 7.8
 - Python version: 3.8
 - EQcorrscan version: 0.4.2  & develop

**Additional context**
I'm not really sure about all the intricate workings of how the correlation is handling padding, NaNs etc., and how this depends on any of the different correlation implementations. But all of the implementations results in the issue described above.

**Comment by calum-chamberlain** [comment]
So the correlation doesn't include correlation of zeros or nan's - possibly uninventively, rather than pad with zeros or nans, traces are trimmed on [this line](https://github.com/eqcorrscan/EQcorrscan/blob/a56711221e5fb0939856b09e9b89f49f5dfb27e4/eqcorrscan/utils/clustering.py#L72). 

This is probably the source of this issue as this can result in the same part of the waveforms not being correlated in one direction. You are right that this is an artefact of the correlations being only computed for the valid (fully overlapping) portion of the waveforms. At the moment your suggested option 3 is pretty much what is done now, and I don't think introducing longer streams would make this problem go away (reliably).

I'm not keen to include correlations including zeros - changing the length of real data correlated can bias the correlations.

What I think we should do is similar to your option 1. I want to retain (regain?) the ability to allow some shift, and I think the best way to do this would be to check for symmetry and just take the smallest distance to make the distance matrix symmetric, e.g.:
```python
for i in range(len(dist_mat)):
    for j in range(len(dict_mat[0])):
        dist = min(dist_mat[i, j], dist_mat[j, i])
        dist_mat[i, j], dist_mat[j, i] = dist, dist
```
There is probably a better way of doing this, rather than looping like this, but this seems to work. Then we would know that we are taking the *best correlation* within some shift (the smallest distance).

What do you think to that?

**Comment by flixha** [comment]
Thanks for the quick input!
With option 3 I really meant something that handles option 2 fully internally, where the code gets access to the waveform that is in front of and behind the template. It should have still been supposed to correlate the same length of the template waveform. 

I think your suggestion is basically what I'd like, it should do its job in the best way and is easy to implement, so I'll do that in a new PR. I may have to do some checking on how different correlation values become at most from what we expect them to be in this implementation.
Cheers!

**Comment by calum-chamberlain** [comment]
It may help to make a positions matrix as well as a distance matrix,  e.g. the shift required to get the max correlation. That might help to show that this works as expected,  and someone might find it a useful output from distance_matrix.

Thanks!

CJ Chamberlain, out of office

________________________________

**Comment by flixha** [comment]
Thanks a lot for merging the related PR to this and awesome job on getting 0.4.3 packaged and published this quickly!
