### ISSUE TITLE
program aborts when plotting with no X window

### ISSUE THREAD

**Issue by dr-glenn** [eqcorrscan/EQcorrscan#469]
Running program in background. Called **detection_multiplot** and only asked for PNG file write. 
Aborted with this error:
_qt.qpa.screen: QXcbConnection: Could not connect to display 128.114.68.14:11.0
Could not connect to any X display._
If program is running in foreground I instead receive a warning - can't remember what it says.

**Expected behavior**
My code:
```
    plotting.detection_multiplot(stplot, st_template, [det.detect_time.datetime,], size=[12.0,10.0],
            title=title,
            return_figure=False,
            show=False, save=True, savefile=plotfile)

```
There's no reason for X windows to be invoked. I also see this problem with **pretty_template_plot**.

**Desktop**
 - Operating System: Centos7 running eqcorrscan, Windows 10 Putty and Xming
 - Python version: 3.7.3
 - EQcorrscan version: 0.3.3

**Possible Fix**
Perhaps if I **import matplotlib** before eqcorrscan and set a backend? If this could fix it, what backend should I use?

**Comment by calum-chamberlain** [comment]
Hi Glenn - the default matplotlib backend here (QT) does require an x-server. I generally import matplotlib and set the backend to 'Agg' - check out [this SO question](https://stackoverflow.com/questions/4931376/generating-matplotlib-graphs-without-a-running-x-server). 

We don't set the backend in EQcorrscan because it is bad practice for an API to set this - a lot of the time you want interactive plots.
