### ISSUE TITLE
get_geonet_events.py

### ISSUE THREAD

**Issue by iceseismic** [eqcorrscan/EQcorrscan#56]
Line 49 in  tutorials/get_geonet_events.py  may possibly need to be : "http://quakesearch.geonet.org.nz/csv?"     as I think GeoNet have changed their calls

**Comment by calum-chamberlain** [comment]
Thanks for that - already patched in [develop](https://github.com/eqcorrscan/EQcorrscan/blob/develop/eqcorrscan/tutorials/get_geonet_events.py#L48) and will be in the next release, just taking a while to make the final additions needed in #55 due to teaching.  If you need any of the updates urgently feel free to install the develop branch (clone the repository, run `git checkout develop` then run `pip install . -U`).

**Comment by calum-chamberlain** [comment]
Made this change in #55, closing in prep for release.
