### ISSUE TITLE
[HELP] Plot MAD threshold 

### ISSUE THREAD

**Issue by GlasG0w** [eqcorrscan/EQcorrscan#569]
Hi there, 

I m using Eqcorrscan since few weeks and I would like to know if it is possible, after doing a tribe.detect_client, to plot the threshold_type MAD to see which threshold value is the best for my case. 

Thanks a lot

# What is your setup? 
 - Operating System:  Darwin
 - Python version: 3.11.8 | packaged by conda-forge
 - EQcorrscan version: 0.5.0

**Comment by calum-chamberlain** [comment]
Kia ora, I'm not sure what you want to plot. You may want to make plots like [this](https://eqcorrscan.readthedocs.io/en/latest/submodules/autogen/eqcorrscan.utils.plotting.triple_plot.html#eqcorrscan.utils.plotting.triple_plot) - if so this can be done automatically by passing the `plot=True` argument to `Tribe.client_detect`. You probably also want to set the `plotdir` argument to save plots to some location rather than having lots of plots pop up on the screen.

If you want to do more with plotting the correlation functions you can pass `export_cccsums=True` as an argument to `Tribe.client_detect` to save out .npy files of the correlation stacks.

**Comment by calum-chamberlain** [comment]
Closed due to inactivity.
