### ISSUE TITLE
Removing short traces in the _download_st function makes client_lag_calc crash

### ISSUE THREAD

**Issue by zhong-yy** [eqcorrscan/EQcorrscan#593]
**Describe the bug**
In the _download_st function, data shorter than 80% of the required length will be removed
https://github.com/eqcorrscan/EQcorrscan/blob/0f687799178aae245236d01a733ca50382d9040a/eqcorrscan/core/match_filter/helpers/tribe.py#L175-L185
Then an empty stream is returned and fed to the lag_calc function,
https://github.com/eqcorrscan/EQcorrscan/blob/0f687799178aae245236d01a733ca50382d9040a/eqcorrscan/core/match_filter/party.py#L926-L936
This will cause IndexError when the stream related attributes are indexed, for example
https://github.com/eqcorrscan/EQcorrscan/blob/0f687799178aae245236d01a733ca50382d9040a/eqcorrscan/utils/pre_processing.py#L800-L803

Is it really necessary to check length of data for lag calculation?

In addition, `_download_st` uses `st.merge()` to merge streams in 
https://github.com/eqcorrscan/EQcorrscan/blob/fa424aae8905464e60f738f08245f169af85a7e4/eqcorrscan/core/match_filter/helpers/tribe.py#L146
and
https://github.com/eqcorrscan/EQcorrscan/blob/fa424aae8905464e60f738f08245f169af85a7e4/eqcorrscan/core/match_filter/helpers/tribe.py#L162
I  worry that it may introduce more gaps because the default merging method (method=0) in obspy treat overlaps as gaps.

**To Reproduce**
In the example of https://github.com/eqcorrscan/EQcorrscan/issues/592, change `lag_calc` to `client_lag_calc`

**Expected behavior**
What I can think of is not to check the data length in `_download_st` function or to check whether the stream is empty in `client_lag_calc`. For example, why not allow the required fraction of the length to be changed, instead of fixing it at 0.8. When this fraction is set to 0 or a negative number, then the length check will be skiped.

**Desktop (please complete the following information):**
 - Operating System: Ubuntu 24.04
 - Python version: python 3.10.14
 - EQcorrscan version: 0.5.dev0

**Additional context**

**Comment by calum-chamberlain** [comment]
1. Length checked in required at some stage to ensure similar processing (particularly similar precision in the FFTs) - checking at download should save time later, but a more appropriate error should be raised if there are no available traces.
2. Merging with method=1 would likely be better to cope with overlaps. However, given that merging and treating overlaps as gaps is the standard throughout EQcorrscan I would be loath to change this. I suggest that if you think you have overlaps then you will need to download the data yourself and manually do what you know you need to do to those overlaps before passing the data to EQcorrscan. It is hard to make a decision that would be correct for all cases when overlaps occur, so this should not be something that EQcorrscan does itself.

**Comment by zhong-yy** [comment]
Thank you for your answers @calum-chamberlain 

Is the cause the same as issue https://github.com/eqcorrscan/EQcorrscan/issues/592? In this issue, the error is caused by the `_download_st` function, while in https://github.com/eqcorrscan/EQcorrscan/issues/592, the error is caused by the `_resample` function or the `_group_process` function.

**Comment by zhong-yy** [comment]
IndexError also occurs in the `client_detect` function. It depends on the value of `process_len`. For my dataset, only `process_len=86400` works, and `process_len=3600` or `21600` will cause the IndexError.

**Comment by zhong-yy** [comment]
Thank you for the fix. Now I don't get the error for `party.lag_calc` in this example. However, if I change the `threshold` of the `tribe.client_detect` or the `process_len` of `tribe.construct`, the error still occurs for `party.client_lag_calc`.

Here is the updated example [issue_592_593.zip](https://github.com/user-attachments/files/18040327/issue_592_593.zip)

In addition, the return catalog of `client_lag_calc` has fewer events than `lag_calc`.

**Comment by calum-chamberlain** [comment]
Thanks for testing that - it looks like the additional detections exposed more issues in `client_lag_calc` around what data was being requested. I just pushed some more changes that I think fix that. The `client_lag_calc` now gets slightly more data than needed from the client and works with that - it returns two fewer events than the straight `lag_calc` version because the last two detections are dropped. Unfortunately there isn't a general way to know when data from a client run out, so it is impossible to set the correct end-times to ensure that all detections have appropriate data.

**Comment by calum-chamberlain** [comment]
Great. 

For the difference between the correlations depending on client or not - no that isn't expected. I might expect some small difference due to numerical precision and the slightly different data that the two methods will work on, but if the differences are larger than about `10**-3` I would be concerned. Can you highlight the differences that you are seeing?

Thanks again.

**Comment by zhong-yy** [comment]
Hi @calum-chamberlain , the difference can be larger than 0.1

![image](https://github.com/user-attachments/assets/7a936c72-261f-4e9f-8115-02c370e3a1b8)

Here is the example [issue_593_diff_max_cc.zip](https://github.com/user-attachments/files/18078676/issue_593_diff_max_cc.zip)

**Comment by calum-chamberlain** [comment]
Detections without picks is to be expected if there were no available picks above your threshold for those detections. The events on the detection objects are edited in place and original picks (which were estimated based on your template picks) should be removed.

The differences in pick correlation values appear to be related to differences in data processing due to different start and end times between the client and non-client method. Changing the sampling rate to 50Hz seems to ameliorate the change in pick times, but differences in pick correlations remain. This likely stems from the filtering of slightly different waveforms giving slightly different correlations. I don't expect to fix this, but it is good to be aware of.

**Comment by zhong-yy** [comment]
Thank you for the explanation. It makes sense to me.
