### ISSUE TITLE
template creation issue from_meta_file

### ISSUE THREAD

**Issue by blazvicic** [eqcorrscan/EQcorrscan#69]
Hi!

I am trying to create a templates from a quakeml file using from_meta_file script.
I am getting error 

> pick.phase_hint, str(pick.time)]))
> TypeError: sequence item 1: expected string or Unicode, NoneType found

On the link, you can get one day data of the stations, script and quakeml file.
quakeml file is generated with obspy from a nonlinloc event file.

https://drive.google.com/open?id=0BzMcKedS7yadSXJCY2o5TDhqVU0

Thanks!

blaz

**Comment by calum-chamberlain** [comment]
Looks like your picks are not associated with any channels - while that is valid quakeML, I wouldn't recommend it here - I haven't ever seen that happen to be honest.  I will add an error message to eqcorrscan, because we need the channel code.  I would recommend assigning each pick to the channel it was made on.

**Comment by calum-chamberlain** [comment]
This issue is now a pull request #70
